### ISSUE TITLE
Feedback part 1:

### ISSUE THREAD

**Issue by Avishti** [mjolca/41189-assignment-template#1]
Feedback on group 4 assignment:
- The use of vocabulary is really good but at times it can become a little bit confusing to read. 
-  “there have been various measures.” of what? Specify what the measure is for and what it’s doing maybe to help clarify this section
- “Systems are defined as a group or assemblage of interconnected units or entities to form a whole.” sounds like this is missing a citation
- What does “PWC” stand for? Maybe put in the full words first then use the abbreviation
- “Outdated static models are preventing problems concerning economic development post-pandemic as static models are not being updated and altered to produce data that is accurate in today’s quickly changing world” very long for an opening/topic sentence. Should cut down.
- “ flu that will pass with warmer seasons” sounds like there’s a missing citation.
- “ predicting the spread rate of the virus alongside the depth of the spread before flatlining” needs more specifying. Feels like it is incomplete. Do you mean flatling the curve? Or maybe use another word other than flatlining.
-  “As a result of this uncertainty adapting current” is missing a comma after uncertainty.
- “Throughout our studies our fellow peers were taught about the ‘supermarket of models’, there are a variety of models that independently conclude on the outcomes and reasons behind such outcomes, the output of this data from an applied study allows us to better predict and delve into complex issues occurring around us.” The topic sentence is very long, and doesn't really make sense.
- “Analyze” z replace with s.
- “The Granovetter's Model is an exceptional model “ is the word ‘exceptional’ necessary? Maybe remove this word because it is known that models are ‘helpful’ and ‘useful’ (maybe use these words instead)
- “sick and tired’ of being ‘trapped’ indoors” sounds like it’s missing a citation 
- “ Australian census to determine the population make up of every suburb and the density of people within a specific region.” - Could possibly add a citation as to where this information came from.
- “Data from the health department “ which health department. Again possible to add a citation from where this information came from.
- “Further iterations” spelling and grammar -  “furthermore” 

- Overall, the report is coming along really well. Some things are not very clear and need clarification (as put above) and some of the topic sentences are very long. It may be a good idea to “get to the point” with shorter and more concise sentences, rather than long and complicated/wordy sentences. The rich-picture diagram is pretty good, especially the images chosen definitely represent COVID-19 and how our world has changed. For section 2.3 you could add a bit more information regarding other perspectives and not just government. Maybe look at societal views and also possibly cultural views to gain a broader understanding. In all, a really good pre-submission and you all should be proud of what you’ve written and created.

**Comment by samhitha123-ship** [comment]
-Elaborate on your stakeholder's section
-The points discussed in the report are valid, however, emphasis on the points is recommended with further explanation of concepts discussed. This will aid in adding depth to your report. 
-The use of academic language is good, however, more sophistication is some areas is required.
